;;; project-tab-test.el --- Tests for project-tab -*- lexical-binding: t -*-

(require 'ert)
(require 'project-tab)

(ert-deftest +project-tab-navigation-survives-manual-rename ()
  (let* ((root (make-temp-file "project-tab-test-" t))
         (default-directory root)
         (file (expand-file-name "one.el" root))
         (expected-root (file-name-as-directory (expand-file-name root)))
         (tab-bar-tab-name-function #'+project-tab-name-tab-function)
         (original-tabs (frame-parameter nil 'tabs))
         (initial-buffer (generate-new-buffer " *project-tab-initial*"))
         buffer)
    (unwind-protect
        (progn
          (make-directory (expand-file-name ".git" root))
          (setq buffer (find-file-noselect file))
          (set-frame-parameter nil 'tabs nil)
          (with-current-buffer initial-buffer
            (setq default-directory temporary-file-directory)
            (setq-local project-find-functions nil))
          (switch-to-buffer initial-buffer)
          (tab-bar-mode 1)
          (funcall tab-bar-tabs-function)
          (should-not (+project-tab--current-root))
          (switch-to-buffer buffer)
          (should (equal expected-root (+project-tab--current-root)))
          (+project-tab-new)
          (+project-tab-new)
          (let ((tabs (funcall tab-bar-tabs-function)))
            (should (equal expected-root (+project-tab--tab-root (nth 0 tabs))))
            (should (equal expected-root (+project-tab--tab-root (nth 1 tabs))))
            (should (equal expected-root (+project-tab--tab-root (nth 2 tabs)))))
          (tab-bar-select-tab 1)
          (+project-tab-next 1)
          (should (= 2 (1+ (tab-bar--current-tab-index))))
          (tab-bar-rename-tab "test")
          (+project-tab-next 1)
          (should (= 3 (1+ (tab-bar--current-tab-index)))))
      (set-frame-parameter nil 'tabs original-tabs)
      (when (buffer-live-p initial-buffer)
        (kill-buffer initial-buffer))
      (when (buffer-live-p buffer)
        (kill-buffer buffer))
      (delete-directory root t))))

(ert-deftest +project-tab-membership-uses-metadata-not-name ()
  (should-not (+project-tab--tab-root '((name . "project:buffer"))))
  (should (equal "/one/project/"
                 (+project-tab--tab-root
                  '((name . "renamed")
                    (+project-tab-root . "/one/project/")
                    (+project-tab-prefix . "project:")))))
  (should-not
   (+project-tab--tab-p
    '((+project-tab-root . "/one/project/")
      (+project-tab-prefix . "same/project:"))
    "/other/project/")))

(ert-deftest +project-tab-project-commands-dispatch-with-metadata-root ()
  (let (called-root excluded-root switched-root pinned-root)
    (cl-letf (((symbol-function '+project-tab-next) #'ignore)
              ((symbol-function '+project-tab-prev) #'ignore)
              ((symbol-function '+project-tab--current-root)
               (lambda () "/metadata/project/"))
              ((symbol-function '+project-tab--current-project-root)
               (lambda () "/metadata/project/"))
              ((symbol-function '+project-tab--project-root) #'identity)
              ((symbol-function '+project-tab--select-other) (lambda () t))
              ((symbol-function '+project-call-project-command)
               (lambda (root) (setq called-root root)))
              ((symbol-function '+project-last-opened-other-project-root)
               (lambda (root)
                 (setq excluded-root root)
                 "/other/project/"))
              ((symbol-function '+project-tab--switch-to-project-and-command)
               (lambda (root) (setq switched-root root)))
              ((symbol-function 'tab-bar-new-tab) #'ignore)
              ((symbol-function '+project-tab--pin-current-project)
               (lambda (root) (setq pinned-root root))))
      (+project-tab-next-project-command 1)
      (should (equal "/metadata/project/" called-root))
      (setq called-root nil)
      (+project-tab-prev-project-command 1)
      (should (equal "/metadata/project/" called-root))
      (setq called-root nil)
      (+project-tab-other-project-command)
      (should (equal "/metadata/project/" called-root))
      (call-interactively #'+project-tab-switch-other-project-command)
      (should (equal "/metadata/project/" excluded-root))
      (should (equal "/other/project/" switched-root))
      (setq called-root nil)
      (+project-tab-new-project-command)
      (should (equal "/metadata/project/" pinned-root))
      (should (equal "/metadata/project/" called-root)))))

(provide 'project-tab-test)
